name: Hifiles Desktop App

env:
  GH_TOKEN: ${{ secrets.GAALO }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app for Windows
        run: npm run build -- --win

      - name: List files in dist directory
        run: dir dist

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: dist/**/*

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app for macOS
        run: npm run build -- --mac

      - name: List files in dist directory
        run: ls -al dist

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: dist/**/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app for Linux (DEB, RPM, AppImage)
        run: npm run build -- --linux deb,rpm,AppImage

      - name: List files in dist directory
        run: ls -al dist

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: dist/**/*

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
          path: dist

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-artifact
          path: dist

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-artifacts
          path: dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.1.5
          release_name: Release v1.1.5
          draft: false
          prerelease: false

      - name: Upload Windows Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hifiles-desktop-app Setup 1.1.5.exe
          asset_name: hifiles-setup-windows-1.1.5.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hifiles-desktop-app-1.1.5-arm64.dmg
          asset_name: hifiles-setup-macos-1.1.5.dmg
          asset_content_type: application/octet-stream

      - name: Upload .deb Linux Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hifiles-desktop-app-1.1.5.deb
          asset_name: hifiles-setup-linux-1.1.5.deb
          asset_content_type: application/octet-stream

      - name: Upload .rpm Linux Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hifiles-desktop-app-1.1.5.rpm
          asset_name: hifiles-setup-linux-1.1.5.rpm
          asset_content_type: application/octet-stream

      - name: Upload AppImage Linux Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hifiles-desktop-app-1.1.5.AppImage
          asset_name: hifiles-setup-linux-1.1.5.AppImage
          asset_content_type: application/octet-stream
